// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { Create1Data, Create1Responses, CreateData, CreateResponses, DeleteByIdData, DeleteByIdResponses, GetIngredientData, GetIngredientResponses, GetIngredientsData, GetIngredientsResponses, GetRecipeData, GetRecipeResponses, GetRecipesData, GetRecipesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get all recipes
 *
 * Returns a paginated list of all available recipes
 */
export const getRecipes = <ThrowOnError extends boolean = false>(options?: Options<GetRecipesData, ThrowOnError>): RequestResult<GetRecipesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetRecipesResponses, unknown, ThrowOnError>({ url: '/recipes', ...options });

/**
 * Creates new recipe
 */
export const create = <ThrowOnError extends boolean = false>(options: Options<CreateData, ThrowOnError>): RequestResult<CreateResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateResponses, unknown, ThrowOnError>({
    url: '/recipes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get all ingredients
 */
export const getIngredients = <ThrowOnError extends boolean = false>(options?: Options<GetIngredientsData, ThrowOnError>): RequestResult<GetIngredientsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetIngredientsResponses, unknown, ThrowOnError>({ url: '/ingredients', ...options });

/**
 * Creates new ingredient
 */
export const create1 = <ThrowOnError extends boolean = false>(options: Options<Create1Data, ThrowOnError>): RequestResult<Create1Responses, unknown, ThrowOnError> => (options.client ?? client).post<Create1Responses, unknown, ThrowOnError>({
    url: '/ingredients',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete recipe by id
 */
export const deleteById = <ThrowOnError extends boolean = false>(options: Options<DeleteByIdData, ThrowOnError>): RequestResult<DeleteByIdResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteByIdResponses, unknown, ThrowOnError>({ url: '/recipes/{recipeId}', ...options });

/**
 * Get recipe by id
 *
 * Returns a recipe for given id
 */
export const getRecipe = <ThrowOnError extends boolean = false>(options: Options<GetRecipeData, ThrowOnError>): RequestResult<GetRecipeResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetRecipeResponses, unknown, ThrowOnError>({ url: '/recipes/{recipeId}', ...options });

/**
 * Get ingredient by id
 */
export const getIngredient = <ThrowOnError extends boolean = false>(options: Options<GetIngredientData, ThrowOnError>): RequestResult<GetIngredientResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetIngredientResponses, unknown, ThrowOnError>({ url: '/ingredients/{ingredientId}', ...options });
