// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}/api` | (string & {});
};

export type ProblemDetail = {
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
    instance?: string;
    properties?: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
};

export type BadRequestProblemDetail = {
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
    instance?: string;
    properties?: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
    /**
     * Validation messages keyed by request field
     */
    errors?: {
        [key: string]: string;
    };
};

export type UpdateRecipeIngredientRequest = {
    id?: string;
    ingredientId: string;
    amount: number;
    unit: string;
    note?: string;
};

export type UpdateRecipeRequest = {
    name: string;
    imageUrl: string;
    description: string;
    sections: Array<UpdateRecipeSectionRequest>;
};

export type UpdateRecipeSectionRequest = {
    id?: string;
    name: string;
    ingredients: Array<UpdateRecipeIngredientRequest>;
};

export type RecipeDto = {
    id: string;
    name: string;
    imageUrl: string;
    description: string;
    sections: Array<RecipeSectionDto>;
    updatedAt: string;
    createdAt: string;
};

export type RecipeIngredientDto = {
    id: string;
    ingredientId: string;
    amount: number;
    unit: string;
    note: string | null;
    position: number;
};

export type RecipeSectionDto = {
    id: string;
    name: string;
    position: number;
    ingredients: Array<RecipeIngredientDto>;
};

export type CreateRecipeIngredientRequest = {
    ingredientId: string;
    amount: number;
    unit: string;
    note?: string;
};

export type CreateRecipeRequest = {
    name: string;
    imageUrl: string;
    description: string;
    sections: Array<CreateRecipeSectionRequest>;
};

export type CreateRecipeSectionRequest = {
    name: string;
    ingredients: Array<CreateRecipeIngredientRequest>;
};

export type CreateIngredientRequest = {
    name: string;
};

export type IngredientDto = {
    id: string;
    name: string;
};

export type UpdateIngredientRequest = {
    name?: string | null;
};

export type PageMetadata = {
    number: number;
    size: number;
    totalElements: number;
    totalPages: number;
};

export type PageResponseRecipeSummaryDto = {
    content: Array<RecipeSummaryDto>;
    page: PageMetadata;
};

export type RecipeSummaryDto = {
    id: string;
    name: string;
    imageUrl: string;
    description: string;
    updatedAt: string;
    createdAt: string;
};

export type PageResponseIngredientDto = {
    content: Array<IngredientDto>;
    page: PageMetadata;
};

export type DeleteRecipeData = {
    body?: never;
    path: {
        recipeId: string;
    };
    query?: never;
    url: '/recipes/{recipeId}';
};

export type DeleteRecipeResponses = {
    /**
     * Recipe deleted or already absent
     */
    204: void;
};

export type DeleteRecipeResponse = DeleteRecipeResponses[keyof DeleteRecipeResponses];

export type GetRecipeData = {
    body?: never;
    path: {
        recipeId: string;
    };
    query?: never;
    url: '/recipes/{recipeId}';
};

export type GetRecipeErrors = {
    /**
     * Requested resource was not found
     */
    404: ProblemDetail;
};

export type GetRecipeError = GetRecipeErrors[keyof GetRecipeErrors];

export type GetRecipeResponses = {
    /**
     * Recipe returned
     */
    200: RecipeDto;
};

export type GetRecipeResponse = GetRecipeResponses[keyof GetRecipeResponses];

export type UpdateRecipeData = {
    body: UpdateRecipeRequest;
    path: {
        recipeId: string;
    };
    query?: never;
    url: '/recipes/{recipeId}';
};

export type UpdateRecipeErrors = {
    /**
     * Request validation failed
     */
    400: BadRequestProblemDetail;
    /**
     * Requested resource was not found
     */
    404: ProblemDetail;
};

export type UpdateRecipeError = UpdateRecipeErrors[keyof UpdateRecipeErrors];

export type UpdateRecipeResponses = {
    /**
     * Recipe updated
     */
    200: RecipeDto;
};

export type UpdateRecipeResponse = UpdateRecipeResponses[keyof UpdateRecipeResponses];

export type GetRecipesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Zero-based page index (0..N)
         */
        page?: number;
        /**
         * The size of the page to be returned
         */
        size?: number;
        /**
         * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         */
        sort?: Array<string>;
    };
    url: '/recipes';
};

export type GetRecipesResponses = {
    /**
     * Recipes returned
     */
    200: PageResponseRecipeSummaryDto;
};

export type GetRecipesResponse = GetRecipesResponses[keyof GetRecipesResponses];

export type CreateRecipeData = {
    body: CreateRecipeRequest;
    path?: never;
    query?: never;
    url: '/recipes';
};

export type CreateRecipeErrors = {
    /**
     * Request validation failed
     */
    400: BadRequestProblemDetail;
    /**
     * Requested resource was not found
     */
    404: ProblemDetail;
};

export type CreateRecipeError = CreateRecipeErrors[keyof CreateRecipeErrors];

export type CreateRecipeResponses = {
    /**
     * Recipe created
     */
    201: RecipeDto;
};

export type CreateRecipeResponse = CreateRecipeResponses[keyof CreateRecipeResponses];

export type GetIngredientsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Zero-based page index (0..N)
         */
        page?: number;
        /**
         * The size of the page to be returned
         */
        size?: number;
        /**
         * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         */
        sort?: Array<string>;
    };
    url: '/ingredients';
};

export type GetIngredientsResponses = {
    /**
     * Ingredients returned
     */
    200: PageResponseIngredientDto;
};

export type GetIngredientsResponse = GetIngredientsResponses[keyof GetIngredientsResponses];

export type CreateIngredientData = {
    body: CreateIngredientRequest;
    path?: never;
    query?: never;
    url: '/ingredients';
};

export type CreateIngredientErrors = {
    /**
     * Request validation failed
     */
    400: BadRequestProblemDetail;
    /**
     * Request conflicts with current resource state
     */
    409: ProblemDetail;
};

export type CreateIngredientError = CreateIngredientErrors[keyof CreateIngredientErrors];

export type CreateIngredientResponses = {
    /**
     * Ingredient created
     */
    201: IngredientDto;
};

export type CreateIngredientResponse = CreateIngredientResponses[keyof CreateIngredientResponses];

export type DeleteIngredientData = {
    body?: never;
    path: {
        ingredientId: string;
    };
    query?: never;
    url: '/ingredients/{ingredientId}';
};

export type DeleteIngredientErrors = {
    /**
     * Request conflicts with current resource state
     */
    409: ProblemDetail;
};

export type DeleteIngredientError = DeleteIngredientErrors[keyof DeleteIngredientErrors];

export type DeleteIngredientResponses = {
    /**
     * Ingredient deleted or already absent
     */
    204: void;
};

export type DeleteIngredientResponse = DeleteIngredientResponses[keyof DeleteIngredientResponses];

export type GetIngredientData = {
    body?: never;
    path: {
        ingredientId: string;
    };
    query?: never;
    url: '/ingredients/{ingredientId}';
};

export type GetIngredientErrors = {
    /**
     * Requested resource was not found
     */
    404: ProblemDetail;
};

export type GetIngredientError = GetIngredientErrors[keyof GetIngredientErrors];

export type GetIngredientResponses = {
    /**
     * Ingredient returned
     */
    200: IngredientDto;
};

export type GetIngredientResponse = GetIngredientResponses[keyof GetIngredientResponses];

export type UpdateIngredientData = {
    body: UpdateIngredientRequest;
    path: {
        ingredientId: string;
    };
    query?: never;
    url: '/ingredients/{ingredientId}';
};

export type UpdateIngredientErrors = {
    /**
     * Request validation failed
     */
    400: BadRequestProblemDetail;
    /**
     * Requested resource was not found
     */
    404: ProblemDetail;
    /**
     * Request conflicts with current resource state
     */
    409: ProblemDetail;
};

export type UpdateIngredientError = UpdateIngredientErrors[keyof UpdateIngredientErrors];

export type UpdateIngredientResponses = {
    /**
     * Ingredient updated
     */
    200: IngredientDto;
};

export type UpdateIngredientResponse = UpdateIngredientResponses[keyof UpdateIngredientResponses];

export type SearchIngredientsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Case-insensitive name fragment
         */
        name: string;
        /**
         * Zero-based page index (0..N)
         */
        page?: number;
        /**
         * The size of the page to be returned
         */
        size?: number;
        /**
         * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         */
        sort?: Array<string>;
    };
    url: '/ingredients/search';
};

export type SearchIngredientsErrors = {
    /**
     * Request validation failed
     */
    400: BadRequestProblemDetail;
};

export type SearchIngredientsError = SearchIngredientsErrors[keyof SearchIngredientsErrors];

export type SearchIngredientsResponses = {
    /**
     * Matching ingredients returned
     */
    200: PageResponseIngredientDto;
};

export type SearchIngredientsResponse = SearchIngredientsResponses[keyof SearchIngredientsResponses];
