// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8080/api' | (string & {});
};

export type CreateRecipeIngredientRequest = {
    ingredientId: string;
    amount: number;
    unit: string;
    note?: string;
};

export type CreateRecipeRequest = {
    name: string;
    imageUrl: string;
    description: string;
    sections: Array<CreateRecipeSectionRequest>;
};

export type CreateRecipeSectionRequest = {
    name: string;
    ingredients: Array<CreateRecipeIngredientRequest>;
};

export type RecipeDto = {
    id?: string;
    name?: string;
    imageUrl?: string;
    description?: string;
    sections?: Array<RecipeSectionDto>;
    updatedAt?: string;
    createdAt?: string;
};

export type RecipeIngredientDto = {
    id?: string;
    ingredientId?: string;
    amount?: number;
    unit?: string;
    note?: string;
    position?: number;
};

export type RecipeSectionDto = {
    id?: string;
    name?: string;
    position?: number;
    ingredients?: Array<RecipeIngredientDto>;
};

export type CreateIngredientRequest = {
    name: string;
};

export type IngredientDto = {
    id?: string;
    name?: string;
};

export type PageMetadata = {
    number?: number;
    size?: number;
    totalElements?: number;
    totalPages?: number;
};

export type PageResponseRecipeSummaryDto = {
    content?: Array<RecipeSummaryDto>;
    page?: PageMetadata;
};

export type RecipeSummaryDto = {
    id?: string;
    name?: string;
    imageUrl?: string;
    description?: string;
    updatedAt?: string;
    createdAt?: string;
};

export type PageResponseIngredientDto = {
    content?: Array<IngredientDto>;
    page?: PageMetadata;
};

export type GetRecipesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Zero-based page index (0..N)
         */
        page?: number;
        /**
         * The size of the page to be returned
         */
        size?: number;
        /**
         * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         */
        sort?: Array<string>;
    };
    url: '/recipes';
};

export type GetRecipesResponses = {
    /**
     * OK
     */
    200: PageResponseRecipeSummaryDto;
};

export type GetRecipesResponse = GetRecipesResponses[keyof GetRecipesResponses];

export type CreateData = {
    body: CreateRecipeRequest;
    path?: never;
    query?: never;
    url: '/recipes';
};

export type CreateResponses = {
    /**
     * Created
     */
    201: RecipeDto;
};

export type CreateResponse = CreateResponses[keyof CreateResponses];

export type GetIngredientsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Zero-based page index (0..N)
         */
        page?: number;
        /**
         * The size of the page to be returned
         */
        size?: number;
        /**
         * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         */
        sort?: Array<string>;
    };
    url: '/ingredients';
};

export type GetIngredientsResponses = {
    /**
     * OK
     */
    200: PageResponseIngredientDto;
};

export type GetIngredientsResponse = GetIngredientsResponses[keyof GetIngredientsResponses];

export type Create1Data = {
    body: CreateIngredientRequest;
    path?: never;
    query?: never;
    url: '/ingredients';
};

export type Create1Responses = {
    /**
     * Created
     */
    201: IngredientDto;
};

export type Create1Response = Create1Responses[keyof Create1Responses];

export type DeleteByIdData = {
    body?: never;
    path: {
        recipeId: string;
    };
    query?: never;
    url: '/recipes/{recipeId}';
};

export type DeleteByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteByIdResponse = DeleteByIdResponses[keyof DeleteByIdResponses];

export type GetRecipeData = {
    body?: never;
    path: {
        recipeId: string;
    };
    query?: never;
    url: '/recipes/{recipeId}';
};

export type GetRecipeResponses = {
    /**
     * OK
     */
    200: RecipeDto;
};

export type GetRecipeResponse = GetRecipeResponses[keyof GetRecipeResponses];

export type GetIngredientData = {
    body?: never;
    path: {
        ingredientId: string;
    };
    query?: never;
    url: '/ingredients/{ingredientId}';
};

export type GetIngredientResponses = {
    /**
     * OK
     */
    200: IngredientDto;
};

export type GetIngredientResponse = GetIngredientResponses[keyof GetIngredientResponses];
