// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { createIngredient, createRecipe, deleteIngredient, deleteRecipe, getIngredient, getIngredients, getRecipe, getRecipes, type Options, searchIngredients, updateIngredient, updateRecipe } from '../sdk.gen';
import type { CreateIngredientData, CreateIngredientError, CreateIngredientResponse, CreateRecipeData, CreateRecipeError, CreateRecipeResponse, DeleteIngredientData, DeleteIngredientError, DeleteIngredientResponse, DeleteRecipeData, DeleteRecipeResponse, GetIngredientData, GetIngredientError, GetIngredientResponse, GetIngredientsData, GetIngredientsResponse, GetRecipeData, GetRecipeError, GetRecipeResponse, GetRecipesData, GetRecipesResponse, SearchIngredientsData, SearchIngredientsError, SearchIngredientsResponse, UpdateIngredientData, UpdateIngredientError, UpdateIngredientResponse, UpdateRecipeData, UpdateRecipeError, UpdateRecipeResponse } from '../types.gen';

/**
 * Delete recipe by id
 *
 * Deletes the recipe when it exists. Repeated requests return no content.
 */
export const deleteRecipeMutation = (options?: Partial<Options<DeleteRecipeData>>): UseMutationOptions<DeleteRecipeResponse, AxiosError<DefaultError>, Options<DeleteRecipeData>> => {
    const mutationOptions: UseMutationOptions<DeleteRecipeResponse, AxiosError<DefaultError>, Options<DeleteRecipeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteRecipe({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getRecipeQueryKey = (options: Options<GetRecipeData>) => createQueryKey('getRecipe', options);

/**
 * Get recipe by id
 *
 * Returns a recipe for given id
 */
export const getRecipeOptions = (options: Options<GetRecipeData>) => queryOptions<GetRecipeResponse, AxiosError<GetRecipeError>, GetRecipeResponse, ReturnType<typeof getRecipeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRecipe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRecipeQueryKey(options)
});

/**
 * Updates entire recipe
 */
export const updateRecipeMutation = (options?: Partial<Options<UpdateRecipeData>>): UseMutationOptions<UpdateRecipeResponse, AxiosError<UpdateRecipeError>, Options<UpdateRecipeData>> => {
    const mutationOptions: UseMutationOptions<UpdateRecipeResponse, AxiosError<UpdateRecipeError>, Options<UpdateRecipeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateRecipe({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getRecipesQueryKey = (options?: Options<GetRecipesData>) => createQueryKey('getRecipes', options);

/**
 * Get all recipes
 *
 * Returns a paginated list of all available recipes
 */
export const getRecipesOptions = (options?: Options<GetRecipesData>) => queryOptions<GetRecipesResponse, AxiosError<DefaultError>, GetRecipesResponse, ReturnType<typeof getRecipesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRecipes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRecipesQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getRecipesInfiniteQueryKey = (options?: Options<GetRecipesData>): QueryKey<Options<GetRecipesData>> => createQueryKey('getRecipes', options, true);

/**
 * Get all recipes
 *
 * Returns a paginated list of all available recipes
 */
export const getRecipesInfiniteOptions = (options?: Options<GetRecipesData>) => {
    const opts = infiniteQueryOptions<GetRecipesResponse, AxiosError<DefaultError>, InfiniteData<GetRecipesResponse>, QueryKey<Options<GetRecipesData>>, number | Pick<QueryKey<Options<GetRecipesData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<GetRecipesData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    page: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await getRecipes({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getRecipesInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

/**
 * Creates new recipe
 */
export const createRecipeMutation = (options?: Partial<Options<CreateRecipeData>>): UseMutationOptions<CreateRecipeResponse, AxiosError<CreateRecipeError>, Options<CreateRecipeData>> => {
    const mutationOptions: UseMutationOptions<CreateRecipeResponse, AxiosError<CreateRecipeError>, Options<CreateRecipeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createRecipe({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getIngredientsQueryKey = (options?: Options<GetIngredientsData>) => createQueryKey('getIngredients', options);

/**
 * Get all ingredients
 */
export const getIngredientsOptions = (options?: Options<GetIngredientsData>) => queryOptions<GetIngredientsResponse, AxiosError<DefaultError>, GetIngredientsResponse, ReturnType<typeof getIngredientsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIngredients({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIngredientsQueryKey(options)
});

export const getIngredientsInfiniteQueryKey = (options?: Options<GetIngredientsData>): QueryKey<Options<GetIngredientsData>> => createQueryKey('getIngredients', options, true);

/**
 * Get all ingredients
 */
export const getIngredientsInfiniteOptions = (options?: Options<GetIngredientsData>) => {
    const opts = infiniteQueryOptions<GetIngredientsResponse, AxiosError<DefaultError>, InfiniteData<GetIngredientsResponse>, QueryKey<Options<GetIngredientsData>>, number | Pick<QueryKey<Options<GetIngredientsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<GetIngredientsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    page: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await getIngredients({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getIngredientsInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

/**
 * Creates new ingredient
 */
export const createIngredientMutation = (options?: Partial<Options<CreateIngredientData>>): UseMutationOptions<CreateIngredientResponse, AxiosError<CreateIngredientError>, Options<CreateIngredientData>> => {
    const mutationOptions: UseMutationOptions<CreateIngredientResponse, AxiosError<CreateIngredientError>, Options<CreateIngredientData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createIngredient({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Deletes ingredient
 *
 * Deletes an unused ingredient. Repeated requests return no content.
 */
export const deleteIngredientMutation = (options?: Partial<Options<DeleteIngredientData>>): UseMutationOptions<DeleteIngredientResponse, AxiosError<DeleteIngredientError>, Options<DeleteIngredientData>> => {
    const mutationOptions: UseMutationOptions<DeleteIngredientResponse, AxiosError<DeleteIngredientError>, Options<DeleteIngredientData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteIngredient({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getIngredientQueryKey = (options: Options<GetIngredientData>) => createQueryKey('getIngredient', options);

/**
 * Get ingredient by id
 */
export const getIngredientOptions = (options: Options<GetIngredientData>) => queryOptions<GetIngredientResponse, AxiosError<GetIngredientError>, GetIngredientResponse, ReturnType<typeof getIngredientQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIngredient({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIngredientQueryKey(options)
});

/**
 * Updates ingredient
 */
export const updateIngredientMutation = (options?: Partial<Options<UpdateIngredientData>>): UseMutationOptions<UpdateIngredientResponse, AxiosError<UpdateIngredientError>, Options<UpdateIngredientData>> => {
    const mutationOptions: UseMutationOptions<UpdateIngredientResponse, AxiosError<UpdateIngredientError>, Options<UpdateIngredientData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateIngredient({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const searchIngredientsQueryKey = (options: Options<SearchIngredientsData>) => createQueryKey('searchIngredients', options);

/**
 * Search ingredients
 */
export const searchIngredientsOptions = (options: Options<SearchIngredientsData>) => queryOptions<SearchIngredientsResponse, AxiosError<SearchIngredientsError>, SearchIngredientsResponse, ReturnType<typeof searchIngredientsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await searchIngredients({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: searchIngredientsQueryKey(options)
});

export const searchIngredientsInfiniteQueryKey = (options: Options<SearchIngredientsData>): QueryKey<Options<SearchIngredientsData>> => createQueryKey('searchIngredients', options, true);

/**
 * Search ingredients
 */
export const searchIngredientsInfiniteOptions = (options: Options<SearchIngredientsData>) => {
    const opts = infiniteQueryOptions<SearchIngredientsResponse, AxiosError<SearchIngredientsError>, InfiniteData<SearchIngredientsResponse>, QueryKey<Options<SearchIngredientsData>>, number | Pick<QueryKey<Options<SearchIngredientsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<SearchIngredientsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    page: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await searchIngredients({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: searchIngredientsInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};
