// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { create, create1, deleteById, getIngredient, getIngredients, getRecipe, getRecipes, type Options } from '../sdk.gen';
import type { Create1Data, Create1Response, CreateData, CreateResponse, DeleteByIdData, DeleteByIdResponse, GetIngredientData, GetIngredientResponse, GetIngredientsData, GetIngredientsResponse, GetRecipeData, GetRecipeResponse, GetRecipesData, GetRecipesResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getRecipesQueryKey = (options?: Options<GetRecipesData>) => createQueryKey('getRecipes', options);

/**
 * Get all recipes
 *
 * Returns a paginated list of all available recipes
 */
export const getRecipesOptions = (options?: Options<GetRecipesData>) => queryOptions<GetRecipesResponse, AxiosError<DefaultError>, GetRecipesResponse, ReturnType<typeof getRecipesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRecipes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRecipesQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getRecipesInfiniteQueryKey = (options?: Options<GetRecipesData>): QueryKey<Options<GetRecipesData>> => createQueryKey('getRecipes', options, true);

/**
 * Get all recipes
 *
 * Returns a paginated list of all available recipes
 */
export const getRecipesInfiniteOptions = (options?: Options<GetRecipesData>) => {
    const opts = infiniteQueryOptions<GetRecipesResponse, AxiosError<DefaultError>, InfiniteData<GetRecipesResponse>, QueryKey<Options<GetRecipesData>>, number | Pick<QueryKey<Options<GetRecipesData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<GetRecipesData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    page: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await getRecipes({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getRecipesInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

/**
 * Creates new recipe
 */
export const createMutation = (options?: Partial<Options<CreateData>>): UseMutationOptions<CreateResponse, AxiosError<DefaultError>, Options<CreateData>> => {
    const mutationOptions: UseMutationOptions<CreateResponse, AxiosError<DefaultError>, Options<CreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await create({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getIngredientsQueryKey = (options?: Options<GetIngredientsData>) => createQueryKey('getIngredients', options);

/**
 * Get all ingredients
 */
export const getIngredientsOptions = (options?: Options<GetIngredientsData>) => queryOptions<GetIngredientsResponse, AxiosError<DefaultError>, GetIngredientsResponse, ReturnType<typeof getIngredientsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIngredients({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIngredientsQueryKey(options)
});

export const getIngredientsInfiniteQueryKey = (options?: Options<GetIngredientsData>): QueryKey<Options<GetIngredientsData>> => createQueryKey('getIngredients', options, true);

/**
 * Get all ingredients
 */
export const getIngredientsInfiniteOptions = (options?: Options<GetIngredientsData>) => {
    const opts = infiniteQueryOptions<GetIngredientsResponse, AxiosError<DefaultError>, InfiniteData<GetIngredientsResponse>, QueryKey<Options<GetIngredientsData>>, number | Pick<QueryKey<Options<GetIngredientsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<GetIngredientsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    page: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await getIngredients({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getIngredientsInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

/**
 * Creates new ingredient
 */
export const create1Mutation = (options?: Partial<Options<Create1Data>>): UseMutationOptions<Create1Response, AxiosError<DefaultError>, Options<Create1Data>> => {
    const mutationOptions: UseMutationOptions<Create1Response, AxiosError<DefaultError>, Options<Create1Data>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await create1({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete recipe by id
 */
export const deleteByIdMutation = (options?: Partial<Options<DeleteByIdData>>): UseMutationOptions<DeleteByIdResponse, AxiosError<DefaultError>, Options<DeleteByIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteByIdResponse, AxiosError<DefaultError>, Options<DeleteByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getRecipeQueryKey = (options: Options<GetRecipeData>) => createQueryKey('getRecipe', options);

/**
 * Get recipe by id
 *
 * Returns a recipe for given id
 */
export const getRecipeOptions = (options: Options<GetRecipeData>) => queryOptions<GetRecipeResponse, AxiosError<DefaultError>, GetRecipeResponse, ReturnType<typeof getRecipeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRecipe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRecipeQueryKey(options)
});

export const getIngredientQueryKey = (options: Options<GetIngredientData>) => createQueryKey('getIngredient', options);

/**
 * Get ingredient by id
 */
export const getIngredientOptions = (options: Options<GetIngredientData>) => queryOptions<GetIngredientResponse, AxiosError<DefaultError>, GetIngredientResponse, ReturnType<typeof getIngredientQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getIngredient({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getIngredientQueryKey(options)
});
